### ISSUE TITLE
Raw use of parameterized class 'Composite'

### ISSUE THREAD

**Issue by McPringle** [alejandro-du/vaadin-auth-example#1]
https://github.com/alejandro-du/vaadin-auth-example/blob/af2ed6470d14ad519d585ade789e6be60fe298e8/src/main/java/com/example/application/views/login/ActivationView.java#L17

For a tutorial, I would suggest fixing the warning at least in this repo.

```java
public class ActivationView extends Composite<VerticalLayout> implements BeforeEnterObserver {
```

```java
@Override
protected VerticalLayout initContent() {
    layout = new VerticalLayout();
    return layout;
}
```

**Comment by alejandro-du** [comment]
Thanks for reporting this. I totally missed it.

Btw, implementing the `initContent()` method is optional when a concrete class is used as a type parameter. I have spoken with developers who pointed out that since the `getContent()` method of `Composite` is public, implementation details are exposed. This can be avoided by using `Component` as the type parameter, in which case implementing the `initContent()` method becomes necessary. I used this last approach to fix the issue.

**Comment by McPringle** [comment]
Perfect, thank you very much!
